services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: ceklab_app
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel_net

  db:
    image: mysql:8.0
    container_name: ceklab_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ceklab
      MYSQL_USER: ceklab_user
      MYSQL_PASSWORD: ceklab_pass
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - laravel_net

  nginx:
    image: nginx:stable-alpine
    container_name: ceklab_nginx_proxy
    ports:
      - "9002:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./src:/var/www/html
    depends_on:
      - app
    networks:
      - laravel_net

networks:
  laravel_net:
    driver: bridge
